# Generated by Django 5.1.4 on 2024-12-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_app', '0002_perfil_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='paixao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='um',
        ),
    ]
