# Generated by Django 5.1.4 on 2024-12-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_app', '0004_perfil_paixao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='paixao',
        ),
    ]
