# Generated by Django 5.1.4 on 2024-12-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_app', '0005_remove_perfil_paixao'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaprofissional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
