# Generated by Django 5.1.4 on 2024-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_app', '0008_remove_servico_descricao_remove_servico_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='views_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
    ]
